In [5]:
import numpy as np

# Các cách tạo array
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((3, 4))          # 3x4 toàn 0
arr3 = np.ones((2, 3))           # 2x3 toàn 1
arr4 = np.random.rand(3, 3)      # 3x3 số ngẫu nhiên 0–1
arr5 = np.arange(0, 10, 2)      # [0, 2, 4, 6, 8]
arr6 = np.linspace(0, 1, 5)      # 5 điểm cách đều từ 0 đến 1

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)


[1 2 3 4 5]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.62401236 0.9409464  0.70851326]
 [0.66856494 0.06334664 0.14688154]
 [0.3784252  0.56107571 0.31817851]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [6]:
# Reshape
arr = np.arange(12)
arr_reshaped = arr.reshape(3, 4)
print("Reshaped:\n", arr_reshaped)

# Transpose
arr_transposed = arr_reshaped.T
print("Transposed:\n", arr_transposed)

# Broadcasting (tính toán với array có kích thước khác nhau)
a = np.array([[1, 2, 3]])
b = np.array([[1], [2], [3]])
broadcasted = a + b
print("Broadcasted:\n", broadcasted)


Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Broadcasted:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
# Dot product, matrix multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product:", dot_product)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
matrix_mult = A @ B
print("Matrix multiplication:\n", matrix_mult)


Dot product: 32
Matrix multiplication:
 [[19 22]
 [43 50]]


In [4]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std:", np.std(data))
print("Var:", np.var(data))
print("Percentile (50th):", np.percentile(data, 50))


Mean: 5.5
Median: 5.5
Std: 2.8722813232690143
Var: 8.25
Percentile (50th): 5.5
